---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.9
    driver_config:
      require_chef_omnibus: false
      provision_command:
        - apt-get update; apt-get -y install build-essential wget net-tools
        - curl -L https://www.opscode.com/chef/install.sh | bash

  - name: debian-8
    driver_config:
      require_chef_omnibus: false
      provision_command:
        - apt-get update; apt-get -y install build-essential wget net-tools
        - curl -L https://www.opscode.com/chef/install.sh | bash

# I must to support centos in future
#  - name: centos-7
#    driver_config:
#      require_chef_omnibus: false
#      provision_command:
#        - yum install -y tar initscripts
#        - curl -L https://www.opscode.com/chef/install.sh | bash
